//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { UsersEntity } from './db/Users.entity';
import { VendorsEntity } from './db/Vendors.entity';
import { CustomersEntity } from './db/Customers.entity';
import { InventoryEntity } from './db/Inventory.entity';
import { ProductsEntity } from './db/Products.entity';
import { ProductCategoriesEntity } from './db/ProductCategories.entity';
import { DiscountsEntity } from './db/Discounts.entity';
import { ShoppingCartEntity } from './db/ShoppingCart.entity';
import { OrdersEntity } from './db/Orders.entity';
import { OrderDetailsEntity } from './db/OrderDetails.entity';
import { PaymentsEntity } from './db/Payments.entity';
import { ReviewsEntity } from './db/Reviews.entity';
import { SupportTicketsEntity } from './db/SupportTickets.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      UsersEntity,
      VendorsEntity,
      CustomersEntity,
      InventoryEntity,
      ProductsEntity,
      ProductCategoriesEntity,
      DiscountsEntity,
      ShoppingCartEntity,
      OrdersEntity,
      OrderDetailsEntity,
      PaymentsEntity,
      ReviewsEntity,
      SupportTicketsEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Users: [
        {
          username: 'username 1',
          email: 'email 1',
          password: 'password 1',
          role: 'role 1',
          id: 55,
        },
        {
          username: 'username 2',
          email: 'email 2',
          password: 'password 2',
          role: 'role 2',
          id: 21,
        },
        {
          username: 'username 3',
          email: 'email 3',
          password: 'password 3',
          role: 'role 3',
          id: 26,
        },
        {
          username: 'username 4',
          email: 'email 4',
          password: 'password 4',
          role: 'role 4',
          id: 34,
        },
        {
          username: 'username 5',
          email: 'email 5',
          password: 'password 5',
          role: 'role 5',
          id: 75,
        },
      ],
      Vendors: [
        {
          companyName: 'companyName 1',
          contactName: 'contactName 1',
          email: 'email 1',
          password: 'password 1',
          id: 53,
        },
        {
          companyName: 'companyName 2',
          contactName: 'contactName 2',
          email: 'email 2',
          password: 'password 2',
          id: 26,
        },
        {
          companyName: 'companyName 3',
          contactName: 'contactName 3',
          email: 'email 3',
          password: 'password 3',
          id: 44,
        },
        {
          companyName: 'companyName 4',
          contactName: 'contactName 4',
          email: 'email 4',
          password: 'password 4',
          id: 39,
        },
        {
          companyName: 'companyName 5',
          contactName: 'contactName 5',
          email: 'email 5',
          password: 'password 5',
          id: 94,
        },
      ],
      Customers: [
        {
          customerName: 'customerName 1',
          email: 'email 1',
          password: 'password 1',
          billingAddress: 'billingAddress 1',
          shippingAddress: 'shippingAddress 1',
          country: 'country 1',
          phone: 'phone 1',
          id: 69,
        },
        {
          customerName: 'customerName 2',
          email: 'email 2',
          password: 'password 2',
          billingAddress: 'billingAddress 2',
          shippingAddress: 'shippingAddress 2',
          country: 'country 2',
          phone: 'phone 2',
          id: 13,
        },
        {
          customerName: 'customerName 3',
          email: 'email 3',
          password: 'password 3',
          billingAddress: 'billingAddress 3',
          shippingAddress: 'shippingAddress 3',
          country: 'country 3',
          phone: 'phone 3',
          id: 88,
        },
        {
          customerName: 'customerName 4',
          email: 'email 4',
          password: 'password 4',
          billingAddress: 'billingAddress 4',
          shippingAddress: 'shippingAddress 4',
          country: 'country 4',
          phone: 'phone 4',
          id: 91,
        },
        {
          customerName: 'customerName 5',
          email: 'email 5',
          password: 'password 5',
          billingAddress: 'billingAddress 5',
          shippingAddress: 'shippingAddress 5',
          country: 'country 5',
          phone: 'phone 5',
          id: 9,
        },
      ],
      Inventory: [
        { product: 1, quantity: 1, lowStockThreshold: 1, id: 92 },
        { product: 2, quantity: 2, lowStockThreshold: 2, id: 3 },
        { product: 3, quantity: 3, lowStockThreshold: 3, id: 59 },
        { product: 4, quantity: 4, lowStockThreshold: 4, id: 86 },
        { product: 5, quantity: 5, lowStockThreshold: 5, id: 25 },
      ],
      Products: [
        {
          productName: 'productName 1',
          vendor: 1,
          price: 0.66,
          weight: 0.22,
          description: 'description 1',
          thumbnail: 'thumbnail 1',
          image: 'image 1',
          category: 1,
          creationDate: '2025-03-02T02:51:12.435Z',
          stock: 1,
          id: 0,
        },
        {
          productName: 'productName 2',
          vendor: 2,
          price: 0.13,
          weight: 0.05,
          description: 'description 2',
          thumbnail: 'thumbnail 2',
          image: 'image 2',
          category: 2,
          creationDate: '2024-02-18T09:40:39.334Z',
          stock: 2,
          id: 72,
        },
        {
          productName: 'productName 3',
          vendor: 3,
          price: 0.83,
          weight: 0.1,
          description: 'description 3',
          thumbnail: 'thumbnail 3',
          image: 'image 3',
          category: 3,
          creationDate: '2023-05-07T10:23:12.311Z',
          stock: 3,
          id: 7,
        },
        {
          productName: 'productName 4',
          vendor: 4,
          price: 0.69,
          weight: 0.45,
          description: 'description 4',
          thumbnail: 'thumbnail 4',
          image: 'image 4',
          category: 4,
          creationDate: '2025-01-31T07:13:29.237Z',
          stock: 4,
          id: 9,
        },
        {
          productName: 'productName 5',
          vendor: 5,
          price: 0.84,
          weight: 0.36,
          description: 'description 5',
          thumbnail: 'thumbnail 5',
          image: 'image 5',
          category: 5,
          creationDate: '2023-12-04T13:15:52.131Z',
          stock: 5,
          id: 85,
        },
      ],
      ProductCategories: [
        { category: 'category 1', id: 21 },
        { category: 'category 2', id: 47 },
        { category: 'category 3', id: 92 },
        { category: 'category 4', id: 96 },
        { category: 'category 5', id: 75 },
      ],
      Discounts: [
        {
          product: 1,
          discountType: 'discountType 1',
          description: 'description 1',
          discountAmount: 0.27,
          discountPercent: 0.57,
          id: 28,
        },
        {
          product: 2,
          discountType: 'discountType 2',
          description: 'description 2',
          discountAmount: 0.73,
          discountPercent: 0.19,
          id: 21,
        },
        {
          product: 3,
          discountType: 'discountType 3',
          description: 'description 3',
          discountAmount: 0.9,
          discountPercent: 0.24,
          id: 40,
        },
        {
          product: 4,
          discountType: 'discountType 4',
          description: 'description 4',
          discountAmount: 0.26,
          discountPercent: 0.95,
          id: 58,
        },
        {
          product: 5,
          discountType: 'discountType 5',
          description: 'description 5',
          discountAmount: 0.11,
          discountPercent: 0.45,
          id: 29,
        },
      ],
      ShoppingCart: [
        { customer: 1, product: 1, priceAtPurchase: 0.31, quantity: 1, id: 65 },
        { customer: 2, product: 2, priceAtPurchase: 0.84, quantity: 2, id: 42 },
        { customer: 3, product: 3, priceAtPurchase: 0.73, quantity: 3, id: 24 },
        { customer: 4, product: 4, priceAtPurchase: 0.93, quantity: 4, id: 3 },
        { customer: 5, product: 5, priceAtPurchase: 0.35, quantity: 5, id: 63 },
      ],
      Orders: [
        {
          orderNumber: 'orderNumber 1',
          customer: 1,
          totalAmount: 0.52,
          vat: 0.07,
          totalAmountWithVat: 0.96,
          shippingCost: 0,
          shippingAddress: 'shippingAddress 1',
          orderAddress: 'orderAddress 1',
          orderEmail: 'orderEmail 1',
          orderDate: '2024-05-10T07:15:20.630Z',
          orderStatus: 'orderStatus 1',
          trackingNo: 'trackingNo 1',
          id: 1,
        },
        {
          orderNumber: 'orderNumber 2',
          customer: 2,
          totalAmount: 0.76,
          vat: 0.31,
          totalAmountWithVat: 0.8,
          shippingCost: 0.21,
          shippingAddress: 'shippingAddress 2',
          orderAddress: 'orderAddress 2',
          orderEmail: 'orderEmail 2',
          orderDate: '2023-05-04T23:00:57.253Z',
          orderStatus: 'orderStatus 2',
          trackingNo: 'trackingNo 2',
          id: 65,
        },
        {
          orderNumber: 'orderNumber 3',
          customer: 3,
          totalAmount: 0.21,
          vat: 0.68,
          totalAmountWithVat: 0.15,
          shippingCost: 0.06,
          shippingAddress: 'shippingAddress 3',
          orderAddress: 'orderAddress 3',
          orderEmail: 'orderEmail 3',
          orderDate: '2025-01-28T02:53:26.464Z',
          orderStatus: 'orderStatus 3',
          trackingNo: 'trackingNo 3',
          id: 8,
        },
        {
          orderNumber: 'orderNumber 4',
          customer: 4,
          totalAmount: 0.78,
          vat: 0.85,
          totalAmountWithVat: 0.22,
          shippingCost: 0.97,
          shippingAddress: 'shippingAddress 4',
          orderAddress: 'orderAddress 4',
          orderEmail: 'orderEmail 4',
          orderDate: '2023-06-22T21:34:11.764Z',
          orderStatus: 'orderStatus 4',
          trackingNo: 'trackingNo 4',
          id: 4,
        },
        {
          orderNumber: 'orderNumber 5',
          customer: 5,
          totalAmount: 0.31,
          vat: 0.14,
          totalAmountWithVat: 0.6,
          shippingCost: 0.09,
          shippingAddress: 'shippingAddress 5',
          orderAddress: 'orderAddress 5',
          orderEmail: 'orderEmail 5',
          orderDate: '2024-12-24T16:26:21.030Z',
          orderStatus: 'orderStatus 5',
          trackingNo: 'trackingNo 5',
          id: 97,
        },
      ],
      OrderDetails: [
        { orderNumber: 1, line: 1, product: 1, price: 0.9, quantity: 1, id: 8 },
        {
          orderNumber: 2,
          line: 2,
          product: 2,
          price: 0.58,
          quantity: 2,
          id: 92,
        },
        {
          orderNumber: 3,
          line: 3,
          product: 3,
          price: 0.18,
          quantity: 3,
          id: 55,
        },
        {
          orderNumber: 4,
          line: 4,
          product: 4,
          price: 0.82,
          quantity: 4,
          id: 47,
        },
        {
          orderNumber: 5,
          line: 5,
          product: 5,
          price: 0.37,
          quantity: 5,
          id: 55,
        },
      ],
      Payments: [
        {
          orderNumber: 1,
          amount: 0.84,
          paymentMethod: 'paymentMethod 1',
          paymentDate: '2023-12-17T15:45:58.279Z',
          paymentStatus: 'paymentStatus 1',
          id: 0,
        },
        {
          orderNumber: 2,
          amount: 0.41,
          paymentMethod: 'paymentMethod 2',
          paymentDate: '2023-12-13T11:05:04.026Z',
          paymentStatus: 'paymentStatus 2',
          id: 5,
        },
        {
          orderNumber: 3,
          amount: 0.1,
          paymentMethod: 'paymentMethod 3',
          paymentDate: '2024-04-08T15:10:06.379Z',
          paymentStatus: 'paymentStatus 3',
          id: 42,
        },
        {
          orderNumber: 4,
          amount: 0.85,
          paymentMethod: 'paymentMethod 4',
          paymentDate: '2023-06-28T19:08:07.993Z',
          paymentStatus: 'paymentStatus 4',
          id: 10,
        },
        {
          orderNumber: 5,
          amount: 0.57,
          paymentMethod: 'paymentMethod 5',
          paymentDate: '2023-07-18T12:45:10.875Z',
          paymentStatus: 'paymentStatus 5',
          id: 64,
        },
      ],
      Reviews: [
        {
          product: 1,
          customer: 1,
          vendor: 1,
          rating: 0.91,
          reviewDetails: 'reviewDetails 1',
          date: '2024-05-17T17:26:02.145Z',
          id: 52,
        },
        {
          product: 2,
          customer: 2,
          vendor: 2,
          rating: 0.39,
          reviewDetails: 'reviewDetails 2',
          date: '2024-08-22T20:22:21.539Z',
          id: 68,
        },
        {
          product: 3,
          customer: 3,
          vendor: 3,
          rating: 0.01,
          reviewDetails: 'reviewDetails 3',
          date: '2024-03-12T15:53:46.653Z',
          id: 47,
        },
        {
          product: 4,
          customer: 4,
          vendor: 4,
          rating: 0.01,
          reviewDetails: 'reviewDetails 4',
          date: '2024-03-14T17:17:15.611Z',
          id: 33,
        },
        {
          product: 5,
          customer: 5,
          vendor: 5,
          rating: 0.55,
          reviewDetails: 'reviewDetails 5',
          date: '2025-03-16T18:04:56.375Z',
          id: 12,
        },
      ],
      SupportTickets: [
        {
          user: 1,
          customer: 1,
          description: 'description 1',
          status: 'status 1',
          creationDate: '2023-09-03T14:30:08.568Z',
          resolutionDate: '2024-08-29T14:49:24.379Z',
          id: 24,
        },
        {
          user: 2,
          customer: 2,
          description: 'description 2',
          status: 'status 2',
          creationDate: '2024-05-17T10:49:26.815Z',
          resolutionDate: '2023-08-12T19:54:48.662Z',
          id: 98,
        },
        {
          user: 3,
          customer: 3,
          description: 'description 3',
          status: 'status 3',
          creationDate: '2023-06-04T06:14:59.165Z',
          resolutionDate: '2024-04-29T19:31:58.789Z',
          id: 63,
        },
        {
          user: 4,
          customer: 4,
          description: 'description 4',
          status: 'status 4',
          creationDate: '2024-08-16T10:01:52.858Z',
          resolutionDate: '2024-09-07T19:09:00.806Z',
          id: 38,
        },
        {
          user: 5,
          customer: 5,
          description: 'description 5',
          status: 'status 5',
          creationDate: '2024-09-03T14:59:54.234Z',
          resolutionDate: '2024-03-10T11:58:28.237Z',
          id: 94,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('UsersEntity', data.Users);
      await this.SeedResource('VendorsEntity', data.Vendors);
      await this.SeedResource('CustomersEntity', data.Customers);
      await this.SeedResource('InventoryEntity', data.Inventory);
      await this.SeedResource('ProductsEntity', data.Products);
      await this.SeedResource(
        'ProductCategoriesEntity',
        data.ProductCategories,
      );
      await this.SeedResource('DiscountsEntity', data.Discounts);
      await this.SeedResource('ShoppingCartEntity', data.ShoppingCart);
      await this.SeedResource('OrdersEntity', data.Orders);
      await this.SeedResource('OrderDetailsEntity', data.OrderDetails);
      await this.SeedResource('PaymentsEntity', data.Payments);
      await this.SeedResource('ReviewsEntity', data.Reviews);
      await this.SeedResource('SupportTicketsEntity', data.SupportTickets);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
